{
 "title": "Zeebe",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_info, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "partition",
    "query": "label_values(zeebe_stream_processor_events_total{namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restarts",
     "type": "graph",
     "description": "Shows when and how often a pod was restarted.  The graph is zero when the pod is ready. With this it is also possible to determine how long it take for the pod to come ready again.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "1 - kube_pod_container_status_ready{pod=~\".*\", pod!~\"curator.*|worker.*|starter.*\", namespace=\"$namespace\"}",
       "legendFormat": "{{pod}} restart"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_ready{container=\"worker\",namespace=\"$namespace\"}[1m])) or vector(1)",
       "legendFormat": "Worker restart"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_ready{container=\"starter\",namespace=\"$namespace\"}[1m])) or vector(1)",
       "legendFormat": "Starter Restart"
      }
     ]
    },
    {
     "title": "Running",
     "type": "table",
     "description": "Displays the current running pods in the namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Processing per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written|processed\"}[1m])) by (pod, partition, processor, action)",
       "legendFormat": "{{pod}}-{{partition}}-{{processor}}-{{action}}"
      },
      {
       "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (pod, partition, exporter)",
       "legendFormat": "{{pod}}-{{partition}}-{{exporter}}"
      }
     ]
    },
    {
     "title": "Completed Processes in avg overtime per sec",
     "type": "singlestat",
     "description": "Takes the avg of all completed processes per second over the given time range.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[1m]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Current Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (type, action)",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Completed Tasks in avg overtime per sec",
     "type": "singlestat",
     "description": "Takes the avg of all completed tasks per second over the given time range.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[1m]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "GRPC Requests handled per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}} Request"
      }
     ]
    },
    {
     "title": "Client Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_started_total{namespace=~\"$namespace\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_client_completed{namespace=~\"$namespace\"}[1m])) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      }
     ]
    },
    {
     "title": "Gateway Backpressure",
     "type": "graph",
     "description": "Shows various metrics related to backpressure applied on a gateway, split per partition. \n\n- inflight counts the current in-flight requests for a given partition\n- dropped counts the total number of requests dropped (i.e. the queue was full)  on a partition\n- received counts the total number of requests (successfully queued AND dropped) that were attempted on a partition\n- queue-limit is the maximum number of in-flight requests at a given point in time for a partition",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_gateway_dropped_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
       "legendFormat": "dropped-{{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_gateway_received_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
       "legendFormat": "received-{{partition}}"
      },
      {
       "expr": "sum(zeebe_gateway_backpressure_requests_limit{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (partition)",
       "legendFormat": "queue-limit-{{partition}}"
      },
      {
       "expr": "zeebe_gateway_backpressure_inflight_requests_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}",
       "legendFormat": "inflight-{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Instance Events per second (range = 1m)",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)"
      }
     ]
    },
    {
     "title": "Job events per second (range = 1m)",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
       "legendFormat": "Stream Processor"
      }
     ]
    },
    {
     "title": "Workflow Instance Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}) by (action)",
       "legendFormat": "Workflow Instance ({{action}})"
      },
      {
       "expr": "sum(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Workflow Instance Events per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)",
       "legendFormat": "Workflow Instance ({{action}})"
      },
      {
       "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Stream Processor Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action, processor)",
       "legendFormat": "{{processor}} ({{action}})"
      },
      {
       "expr": "sum(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action, processor)",
       "legendFormat": "exporter ({{action}})"
      }
     ]
    },
    {
     "title": "Stream Processor Events per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action, processor)",
       "legendFormat": "{{processor}} ({{action}})"
      },
      {
       "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action, processor)",
       "legendFormat": "exporter ({{action}})"
      }
     ]
    },
    {
     "title": "Running Workflow Instances",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_running_workflow_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
       "legendFormat": "Workflow Instance"
      },
      {
       "expr": "sum(zeebe_pending_jobs_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
       "legendFormat": "Jobs"
      },
      {
       "expr": "sum(zeebe_pending_incidents_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
       "legendFormat": "Incidents"
      }
     ]
    },
    {
     "title": "Stream Processor vs Exporter",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\", action=~\"skipped|processed\", partition=~\"$partition\", pod=~\"$pod\"}) - sum(zeebe_exporter_events_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"})",
       "legendFormat": "Events processed but not exported"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} RSS"
      }
     ]
    },
    {
     "title": "JVM Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
       "legendFormat": "{{pod}} JVM heap"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"\", namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Buffer Pool Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (jvm_buffer_pool_used_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace,pod,pool)",
       "legendFormat": "Used {{pod}}:{{pool}}"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\"} / process_max_fds{namespace=~\"$namespace\",pod=~\"$pod\"}) * 100",
       "legendFormat": "{{pod}} used fds"
      },
      {}
     ]
    },
    {
     "title": "PVC Disk Available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}} ({{namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read bytes/s [1m]",
     "type": "graph",
     "description": "Shows the bytes read per second for the zeebe pods in the select namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Written bytes/s [1m]",
     "type": "graph",
     "description": "Shows the written bytes per second by the Zeebe pods in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s transmitted [1m]",
     "type": "graph",
     "description": "Shows how many bytes the Zeebe Pods transmit per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s received [1m]",
     "type": "graph",
     "description": "Shows how many bytes the Zeebe Pods have received per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Latency (Command)",
     "type": "heatmap",
     "description": "Shows the time (latency) between writing the command on the dispatcher and processing it.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\", recordType=\"COMMAND\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing Latency (Event)",
     "type": "heatmap",
     "description": "Shows the time (latency) between writing the event on the dispatcher and processing it.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\", recordType=\"EVENT\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing Execution Time",
     "type": "heatmap",
     "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_workflow_instance_execution_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Job Activation Time",
     "type": "heatmap",
     "description": "Shows the time (latency) between creating the job and activating it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_job_activation_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Job Life Time",
     "type": "heatmap",
     "description": "Shows the complete lifetime of an job. This means the time (latency) between creating the job and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_job_life_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      }
     ]
    },
    {
     "title": "gRPC requests per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "Total requests completed"
      }
     ]
    },
    {
     "title": "Create Workflow Instance Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"CreateWorkflowInstance\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Activate Jobs Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"ActivateJobs\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Complete Job Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"CompleteJob\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}